[package]
name = "einput_output_vigem"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
einput_core = { path = "../einput_core" }
einput_device = { path = "../einput_device" }
einput_util = { path = "../einput_util" }
log = "0.4.21"
vigem-client = "0.1.4"
